services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: aioceaneye/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - drone-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: aioceaneye/backend:latest
    ports:
      - "8080:8080"
      - "14552-14559:14552-14559/udp"
      - "15000-15009:15000-15009/udp"
    networks:
      - aioceaneye-network

networks:
  drone-network:
    driver: bridge