version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - drone-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "14552-14559:14552-14559/udp"
      - "15000-15009:15000-15009/udp"
    volumes:
      - ./Backend/logs:/app/logs  # This must be present
    networks:
      - drone-network

networks:
  drone-network:
    driver: bridge