version: '3.8'

services:
  frontend:
    image: 221082202241.dkr.ecr.ap-southeast-1.amazonaws.com/aioceaneye/frontend:dev
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - drone-network

  backend:
    image: 221082202241.dkr.ecr.ap-southeast-1.amazonaws.com/aioceaneye/backend:dev
    ports:
      - "8080:8080"
      - "14552-14559:14552-14559/udp"
      - "15000-15009:15000-15009/udp"
    volumes:
      - ./Backend/logs:/app/logs
    networks:
      - drone-network

networks:
  drone-network:
    driver: bridge