import { useSelector } from "react-redux";

export const translations = {
    ENG: {
      // LoginForm translations (previous)
      lang: "ENG",
      welcome: "Welcome",
      signIn: "Sign in to your account",
      usernameOrEmail: "User name or E-mail",
      usernameOrEmailPlaceholder: "User name or E-mail",
      password: "Password",
      passwordPlaceholder: "Password",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      login: "Login",
      newMember: "New member?",
      register: "Register",
      emailRequired: "Email is required",
      passwordRequired: "Password is required",
  
      // UserRegister translations (new)
      membershipRegister: "Membership Register",
      name: "Name",
      namePlaceholder: "Please Enter Name",
      email: "E-mail",
      emailPlaceholder: "Please Enter Email",
      certified: "Certified",
      reCertified: "Re-Certified",
      emailCheckPlaceholder: "Please Enter",
      check: "Check",
      passwordCheck: "Password Check",
      confirmPassword: "Confirm Password",
      userRating: "User Rating",
      company: "Company",
      companies: "Companies",
      captain: "Captain",
      pilot: "Pilot",
      mechanic: "Mechanic",
      phoneNo: "Phone No",
      cancel: "Cancel",
      save: "Save",

      //Find Password translations
      findPassword: "Find PW",
      next: "Next",

      //Side Bar Translations
      flightMap: "Flight Map",
      information: "Information",
      vessels: "Vessels",
      drone: "Drone",
      material: "Material",
      work: "Work",
      flightRecord: "Flight Record",
      workAssignment: "Work Assignment",
      pilotWorkSchedule: "Work Schedule",
      report: "Report",
      document: "Document",
      dashboard: "Dashboard",
      flightLog: "Flight Log",
      videoGallery: "Video Gallery",
      helpCenter: "Help Center",

      //others
      list: "List",
      quickSearch: "Quick Search",
      vesselsInfo: "Vessels Info",
      video: "Video",
      wayPoints : "Waypoint",
      country: "Country",
      mate: "Mate",
      yield: "Yield",
      latitude: "Latitude",
      longitude: "Longitude",
      droneInfo: "Drone Info",
      model: "Model",
      serialNumber: "Serial No",
      droneID: "Drone ID",
      pilotInfo: "Pilot Info",
      internalPilot: "Internal Pilot",
      externalPilot: "External Pilot",

      //Info translations
      businessNo: "Business No",
      representative: "Representative",
      logo: "Logo",
      homePage: "Home Page",
      establishmentYear: "Establishment Year",
      employees: "Employees",
      address: "Address",
      faxNo: "FAX No",
      image: "Image",
      pleaseSelect: "Please Select",
      file: "File",
      overView: "Overview",
      registration: "Register",
      uploadLogoImage: "Upload Logo Image",
      detail: "Details",
      delete: "Delete",
      edit: "Edit",
      record: "Record",
      date: "Date",
      area: "Area",
      loadDrone: "Load Drone",
      imageUpload: "Image Upload",
      employeeNo: "Employee No",
      certificateNo: "Certificate No",
      flightNo: "Flight No",
      flightDistance: "Flight Distance",
      flightTime: "Flight Time",
      passportNo: "Passport No",
      fishingMount: "Fishing Mount",
      pilotPosition: "Pilot Position",
      droneDetailInfo: "Drone Detail Info",
      stockDate: "Stock Date",
      estimateRestTime: "Estimate Rest Time",
      useTime: "Use Time",
      materialRestTime: "Material Rest Time",
      specifications: "Specifications",
      manufacturer: "Manufacturer",
      kind: "Kind",
      size: "Size",
      weight: "Weight",
      maxAltitude: "Max Altitude",
      maxRadius: "Max Radius",
      flightSpeed: "Flight Speed",
      specificationsInfoEdit: "Specifications Info Edit",
    },
    KOR: {
      // LoginForm translations (previous)
      lang: "KOR",
      welcome: "Welcome",
      signIn: "반갑습니다! 로그인을 진행해주세요.",
      usernameOrEmail: "이메일",
      usernameOrEmailPlaceholder: "이메일을 입력하세요.",
      password: "비밀번호",
      passwordPlaceholder: "비밀번호를 입력하세요",
      rememberMe: "기억하기",
      forgotPassword: "ID찾기",
      login: "로그인",
      newMember: "아직 회원이 아니신가요?",
      register: "회원가입",
      emailRequired: "이메일은 필수입니다",
      passwordRequired: "비밀번호는 필수입니다",
  
      // UserRegister translations (new)
      membershipRegister: "회원 등록",
      name: "이름",
      namePlaceholder: "이름을 입력해주세요",
      email: "이메일",
      emailPlaceholder: "이메일을 입력해주세요",
      reCertified: "인증번호 전송",
      emailCheckPlaceholder: "입력해주세요",
      check: "인증번호 확인",
      passwordCheck: "비밀번호 확인",
      confirmPassword: "비밀번호 확인",
      userRating: "사용자 등급",
      company: "선사",
      companies: "선사명",
      captain: "선장",
      pilot: "조종사",
      mechanic: "정비사",
      phoneNo: "전화번호",
      cancel: "취소",
      save: "저장",

      //Find Password translations
      findPassword: "비밀번호 찾기",
      next: "다음",

      //Side Bar Translations
      flightMap: "실시간 비행정보",
      information: "정보등록",
      vessels: "선박",
      drone: "드론",
      material: "자재",
      work: "업무등록",
      flightRecord: "비행기록",
      workAssignment: "업무배정",
      pilotWorkSchedule: "조종자근무스케줄",
      report: "보고서작성",
      document: "문서",
      dashboard: "대시보드",
      flightLog: "비행로그",
      videoGallery: "비디오갤러리",
      helpCenter: "도움센터",

      //others
      list: "리스트",
      quickSearch: "검색어를 입력하세요.",
      vesselsInfo: "선박정보",
      video: "비디오",
      wayPoints : "비행경로",
      country: "국가",
      mate: "항해사",
      yield: "조업기여량",
      latitude: "위도",
      longitude: "경도",
      droneInfo: "기체정보",
      model: "모델명",
      serialNumber : "제작번호",
      droneID : "기체ID",
      pilotInfo: "조종자정보",
      internalPilot: "내부조종자",
      externalPilot: "외부조종자",

      //company info translations
      businessNo: "사업자번호",
      representative: "담당자명",
      logo: "로고",
      homePage: "홈페이지",
      establishmentYear: "설립년도",
      employees: "종업원수",
      address: "주소",
      faxNo: "FAX 번호",
      image: "이미지",
      pleaseSelect: "선택해주세요",
      file: "등록증",
      overView: "목록",
      registration: "등록",
      uploadLogoImage: "로고 이미지 업로드",
      detail: "상세정보",
      delete: "삭제",
      edit: "수정",
      record: "기록",
      date: "날짜",
      area: "지역",
      loadDrone: "탑재드론",
      imageUpload: "이미지 업로드",
      employeeNo: "사원번호",
      certificateNo: "자격증번호",
      flightNo: "비행횟수",
      flightDistance: "비행거리",
      flightTime: "비행시간",
      passportNo: "여권번호",
      fishingMount: "조업기여량",
      pilotPosition: "조종포지션",
      droneDetailInfo: "기체상세정보",
      materialInfo: "부품정보",
      stockDate: "입고날짜",
      estimateRestTime: "예상교체시간",
      useTime: "사용시간",
      materialRestTime: "부품교체잔여시간",
      specifications: "제원",
      manufacturer: "제조사",
      kind: "종류",
      size: "크기",
      maxAltitude: "최대운용고도",
      weight: "자체중량",
      maxRadius: "최대운용반경",
      flightSpeed: "비행속도",
      specificationsInfoEdit: "제원 정보 수정",
    }
  };
  
  // Custom hook for accessing translations
  export const useTranslations = () => {
    const selector = useSelector;
    const currentLanguage = selector((state) => state.language.currentLanguage);
    return translations[currentLanguage];
  };

  export default useTranslations;